[project]
name = "llm-logistic"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.141.1",
    "langchain>=1.4.0",
    "langchain-community>=0.4.2",
    "langchain-openai>=1.6.0",
    "modelscope>=1.39.1",
    "openai>=3.8.0",
    "openpyxl>=3.1.5",
    "pypdf>=6.18.0",
    "python-docx>=1.2.0",
    "python-dotenv>=1.2.3",
    "pyyaml>=6.0.3",
    "torch>=2.5.1",
    "transformers>=5.16.1",
    "uvicorn[standard]>=0.30.0",
]

[[tool.uv.index]]
name = "pytorch-cu121"
url = "https://download.pytorch.org/whl/cu121"
explicit = true

[tool.uv.sources]
torch = [
  { index = "pytorch-cu121", marker = "sys_platform == 'linux' or sys_platform == 'win32'" },
]
torchvision = [
  { index = "pytorch-cu121", marker = "sys_platform == 'linux' or sys_platform == 'win32'" },
]

